# Root directory where all pipeline artifacts (e.g., raw data, models) will be stored
artifacts_root: artifacts

# Configuration specific to the Data Ingestion stage. This is where the data will be downloaded and unzipped
data_ingestion:
  root_dir: artifacts/data_ingestion # Subdirectory for all data ingestion outputs (downloaded file, extracted contents)
  source_URL: https://drive.google.com/file/d/18lYwMich8AZeG8K7r9s8FB31NlIh1XYc/view?usp=sharing
  local_data_file: artifacts/data_ingestion/data.zip # Path to the downloaded data file
  unzip_dir: artifacts/data_ingestion # Directory where the unzipped data will be stored

# Prepare base model
prepare_base_model:
  root_dir: artifacts/prepare_base_model # Subdirectory for all base model outputs
  base_model_path: artifacts/prepare_base_model/base_model.h5 # Path to the base model file
  updated_base_model_path: artifacts/prepare_base_model/base_model_updated.h5 # Path to the updated base model with custom layer added

# Training configuration
training:
  root_dir: artifacts/training # Subdirectory for all training outputs
  trained_model_path: artifacts/training/model.h5 # Path to the trained model file

